<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // const p = new Promise((resolve,reject) => {
    //   setTimeout(()=>{
    //     // resolve('成功了')
    //     reject('出错了')
    //   },1000)
    // })
    // const  result = p.then(value => {
    //   // return 112233;
    //   // return new Promise((resolve,reject) => {
    //   //   // resolve('112233')
    //   //   reject('出错了')
    //   // })
    //   // throw new Error('出错啦！')
    //   // throw '出错了'
    // },reason => { 
    //   console.warn(reason)
    // })

    // console.log(result)

    /* .catch 返回的是一个状态为fufulfilled，result为undefined的promise */
    // console.log(Promise.reject().catch(err =>{
    //   console.warn(err);
    //   return '112233'
    // }).then((value)=>console.log('22',value)))

  </script>
</body>
</html>